### ISSUE TITLE
error on pas install

### ISSUE THREAD

**Issue by alfathdirk** [xinix-technology/pas#28]
alfathdirk@alfathdirk:~/workspace/test$ pas install
Cannot find module '/home/alfathdirk/workspace/test/pas-development.json'

while pas install on php project

**Comment by reekoheek** [comment]
Please make sure this issue still happening at your system and then provide returned value for following commands:

1

```
pas
```

2

```
pas config
```

3

```
pas plugin
```

4

```
cat ~/.pas/config.json
```

**Comment by reekoheek** [comment]
wont be issue anymore
